spring.datasource.url=jdbc:mysql://localhost:3306/PRJ-ST2OOS
spring.datasource.username=nicolaslahimasy
spring.datasource.password=nicolaslahimasy123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
